### ISSUE TITLE
Convert to Use JWKs and a Bare Key

### ISSUE THREAD

**Issue by aviars** [HHSIDEAlab/python-poetri#2]
POETRI will use raw private keys (for signing) and JWKs as public keys instead of x509 certificates.  You will likely need to explore other library options to make this work.

**Comment by flowersw** [comment]
@aviars , for sign_poet.py

Do the headers and payload still need to be encrypted together?
I guess my question is the jwt encoder had an argument for headers, but a traditional encrypter like rsa doesn't have that functionality.

I could put the headers and payload into one dict, or just encrypt the payload

Thoughts or suggestions?

**Comment by aviars** [comment]
Let's discuss tomorrow. I don't think adding the header to the payload is correct.

**Comment by aviars** [comment]
Done cc/ @jmandel @jricher
